### ISSUE TITLE
support for database/sql.Scanner and database/sql/driver.Valuer

### ISSUE THREAD

**Issue by phenpessoa** [VinGarcia/ksql#39]
Does this lib offers support for `database/sql.Scanner` and `database/sql/driver.Valuer` interfaces for custom types?

Custom use case is for null fields where you don't want to (or can't) add pointers, for example.

`database/sql.NullTime` is one of the most famous use cases.

**Comment by VinGarcia** [comment]
Hey @phenpessoa sorry for the delay I missed the email notification. Yes, it does. But what do you mean by custom types?

**Comment by phenpessoa** [comment]
Hey @VinGarcia no worries!
For example, with [pgx](https://github.com/jackc/pgx) we can use [decimal](https://github.com/shopspring/decimal) for `Numeric` values on PostgreSQL. This is thanks to `database/sql.Scanner` and `database/sql/driver.Valuer`.

But I can create any custom type I want and serialize/deserialize them to/from the database as long as they implement those interfaces. 

Check [this PR](https://github.com/jackc/pgx/commit/9f9a9779ac794e885f6fbb04935724f03149f092) for an example.

**Comment by VinGarcia** [comment]
Also just so you understand what I mean about a modifier:

https://github.com/VinGarcia/ksql/wiki/Modifiers

It is an extra annotation on the `ksql` tag. e.g.: `ksql:"address,json"`

The modifier can specify a scanner and/or valuer function so if it does we will use that instead of the .Scan or .Value functions of your type, at least that is how it is right now. I may be able to check if the original type implements Scan and/or Value and call this function myself inside the modifier functions.

**Comment by VinGarcia** [comment]
Hey @phenpessoa, I finally improved the docs on this, on the README I am now mentioning it as an outstanding feature:

https://github.com/VinGarcia/ksql#outstanding-features

And I also updated the "Modifiers" Wiki page to explain that KSQL supports the Scanner and Valuer interfaces and also explain the differences between these interfaces and the Modifiers:

https://github.com/VinGarcia/ksql/wiki/sql.Scan,-sql.Value-and-Modifiers

**Comment by VinGarcia** [comment]
I will leave this Issue open for a few days, if you want me to add anything to these docs just say so. After that, I will close the issue but feel free to create a new one at any time.

Kind Regards.

**Comment by phenpessoa** [comment]
I think the docs now make it crystal clear. Thank you!

**Comment by VinGarcia** [comment]
Nice, I will close this issue then, feel free to open others whenever you need =]
