### ISSUE TITLE
How to execute an update using ANY query param with string slice

### ISSUE THREAD

**Issue by leonardorifeli** [VinGarcia/ksql#49]
We need to execute an update using `id IN ($1)` or `id = ANY($1)` with `pg.Array([]string{"123","1234"}`.

How to do that?

Example:

```golang
// NOT WORKING
func Update(data []string) {
   query := "UPDATE people SET isValid = true WHERE id = ANY($1);";
   _, err := db.Exec(ksql.InjectLogger(context.Background(), ksql.Logger), query, pq.Array(data))
}
```

**Comment by leonardorifeli** [comment]
We (@HarmoDeveloper) want to sponsor you @VinGarcia!

**Comment by leonardorifeli** [comment]
Since `pg.Array` receives an `interface{}`, we sent a parsed `[]string` from a query parameter.
We adjusted for a JSON payload by using `ShouldBindJSON`, and it worked.

**Comment by VinGarcia** [comment]
Hey @leonardorifeli, I apologize for missing your comments, I just noticed them now. I do sometimes miss some email notifications.

Yeah I do like the idea of being sponsored, I am actually trying to find options right now to dedicate more time to projects like this one.

That said, I would totally understand if the sponsoring you offered is not available anymore.

If you are still interested in talking about this you can send me an email to vingarcia00@gmail.com

I have some interesting ideas for a v2 of this repo and I also have other projects and we can talk about it.

In any case, thanks for reaching out, and feel free to contact me or create a new issue.

**Comment by VinGarcia** [comment]
@leonardorifeli I just enabled Github Sponsoring for this repo =].

**Comment by leonardorifeli** [comment]
Now we are your sponsors! Me and @harmodeveloper

**Comment by VinGarcia** [comment]
Hey @leonardorifeli  thanks! and @HarmoDeveloper too =]
